project:
  type: website

website:
  title: "Workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: agenda.qmd
        text: Agenda
      - href: bioinformatics.qmd
        text: Bioinformatics
      - text: Training materials
        menu:
          - module1/module1.qmd
          - resources.qmd


  page-footer: 
    left: "This work is licensed under a Creative Commons Attribution 4.0 International License. Reuse is encouraged with acknowledgement" 
    right: 
      - icon: twitter 
        href: https://twitter.com/TheCGPS


format:
  html:
    theme: sketchy 
    anchor-sections: true

editor: visual

execute:
  freeze: auto
  
sidebar:
  contents: auto

link-external-newwindow: true
